### ISSUE TITLE
"Undefined variable" message after activation

### ISSUE THREAD

**Issue by Mat2012** [Getbeans/Beans#1]
Thanks for this very nice project !

I have this error message once the theme activated, just above the navigation, in the header 

Notice: Undefined variable: link_attr in /Applications/MAMP/htdocs/mywebsite/wp-content/themes/Beans-master/lib/render/walker.php on line 118

**Comment by ThierryA** [comment]
Hey Mat, thanks for reporting the issue. It will be fixed within the next 5 hours. I will notify you once it is done.

Thanks,

**Comment by ThierryA** [comment]
Hi Mat,

I just pushed the fix. There is another small modification I would like to apply to the updater and I will officially release 1.1.2.

Thanks,

**Comment by Mat2012** [comment]
Thanks you, I'll have a look.

**Comment by Mat2012** [comment]
The message has disappeared, it's ok now. Thanks Thierry !
