### ISSUE TITLE
CSS minify when Compiling all assets into one file

### ISSUE THREAD

**Issue by gabormeszoly** [Getbeans/Beans#11]
Hi Beans,
There is some options to compress the CSS to?
Thanks, Gabor
p.s.: beans is awesome

**Comment by ThierryA** [comment]
Hi @gabormeszoly,

You may enqueue your own compiler using the [beans_compile_css_fragments()](http://www.getbeans.io/code-reference/functions/beans_compile_css_fragments/) function which should be use like the [wp_enqueue_script()](http://codex.wordpress.org/Function_Reference/wp_enqueue_script) except that the second argument can be an array of files to compile.

Alternatively you could simply enqueue all your CSS file as normal and simply enable the **"Compile all WordPress styles"** under **Appearance->Settings** when you are ready to go live. This will grab all the CSS files enqueued (include third party plugins), compile it into one file, and cache it on a per-page-basis.

Hope that helps :-)

**Comment by gabormeszoly** [comment]
“If you haven't found the magic in Beans, you haven't looked far enough!”
:) Thanks mate

**Comment by ThierryA** [comment]
That is correct :-) Thanks buddy!
