### ISSUE TITLE
Wrong image path in Multisite Post Options metabox

### ISSUE THREAD

**Issue by gabormeszoly** [Getbeans/Beans#16]
It looks like this:
```
http://beans-multisite.dev/site/wp-content/themes/tm-beans/lib/admin/assets/images/layouts/c.png
http://beans-multisite.dev/site/wp-content/themes/tm-beans/lib/admin/assets/images/layouts/cs.png
http://beans-multisite.dev/site/wp-content/themes/tm-beans/lib/admin/assets/images/layouts/sc.png
http://beans-multisite.dev/site/wp-content/themes/tm-beans/lib/admin/assets/images/layouts/css.png
http://beans-multisite.dev/site/wp-content/themes/tm-beans/lib/admin/assets/images/layouts/ssc.png
http://beans-multisite.dev/site/wp-content/themes/tm-beans/lib/admin/assets/images/layouts/scs.png
```

**Comment by ThierryA** [comment]
Hey @gabormeszoly,

The paths looks correct to me, is your install in a `site` folder? What should the path be for that install?

Thanks,

**Comment by gabormeszoly** [comment]
Hi @ThierryA 
I did a local version and everything is fine, probably my remote install has something wrong.
Sorry for that ...

**Comment by ThierryA** [comment]
No worries, please do not hesitate to report if you can reproduce it :)

**Comment by frankomator** [comment]
Hi @gabormeszoly, can you share your solution? I've got the same problem. Only the (correct) paths to the layout images are shown in the Customizer and in the Post Options but not the images themselves.
![screenshot](https://cloud.githubusercontent.com/assets/3018128/11335548/56f17ab4-91dd-11e5-9b49-0bd7f42ba77e.png)

**Comment by ThierryA** [comment]
Alright guys, this is due to the `getimagesize()` which is not picking up that it is an image and therefore displaying the option as a radio button. I will push a fix and keep you updated so that you can do some testing.

Thanks,

**Comment by gabormeszoly** [comment]
This problem comes up when the site is authorised. Example:
`Warning: getimagesize(http://congressline-multisite.dev.templatebooster.com/event2020/wp-content/themes/tm-beans/lib/admin/assets/images/layouts/c.png): failed to open stream: HTTP request failed! HTTP/1.1 401 Authorization Required in /var/www/dev.templatebooster.com/congressline-multisite/wp-content/themes/tm-beans/lib/api/fields/types/radio.php on line 38`

@frankomator remove the '@' char from: https://github.com/Getbeans/Beans/blob/master/lib/api/fields/types/radio.php#L38 to php debug info.

Ofc, set `define('WP_DEBUG', true);`

**Comment by frankomator** [comment]
Thanks for the hint. But I've get a different error message then: 
<pre>"Warning: getimagesize(): http:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /kunden/mediaworkers.de/webseiten/testground/dev/site/wp-content/themes/tm-beans/lib/api/fields/types/radio.php on line 38"</pre>

Setting "allow_url_fopen = 1" actually solves the problem for me, but leaves the server vulnerable to xss injections. I'd better wait for the fix.

**Comment by gabormeszoly** [comment]
Hi @ThierryA @frankomator 
I sent a PR for this problem.
Thanks, Gabor

**Comment by frankomator** [comment]
Thank you, it seems one dot is missing in lib/api/fields/types/radio.php line 43:
echo '<img src="' BEANS_ADMIN_ASSETS_URL . '/' . $radio . '" />';
should be:
echo '<img src="' . BEANS_ADMIN_ASSETS_URL . '/' . $radio . '" />';
Everything works fine in "Post Options" then, but in the Customizer the layouts cannot be changed.

**Comment by frankomator** [comment]
Correction: Customizer works also now.

**Comment by ThierryA** [comment]
Hi @frankomator @gabormeszoly,

I am going to start working on this issue in about an hour and will report once I push a fixed.

@gabormeszoly thanks for the PR but it is unfortunately not the correct approach, I will explain why on the PR. For me to understand better the issue on your install, could you advise how `http://congressline-multisite.dev.templatebooster.com` plays in your setup? What is your local domain and what is `templatebooster.com`?

Thanks,

**Comment by ThierryA** [comment]
Hey @frankomator, I pushed a fix which should solve your issue 01ce2b8. Please grab the latest version from the repo and take it for a spin.

@gabormeszoly please advise if you still have the path issue and if yes, please let me know what is your domain and subfolder structure so that I can try replicating it.

Thanks,

**Comment by gabormeszoly** [comment]
Hi @ThierryA 
Everything is ok, both the customizer and the post options meta.
Thanks, Gabor

**Comment by ThierryA** [comment]
Great, thanks for testing it :)

**Comment by frankomator** [comment]
Everything okay now - thank you for the quick fix.
