### ISSUE TITLE
Conditionnally change layout

### ISSUE THREAD

**Issue by Mat2012** [Getbeans/Beans#19]
Hello,

I'd like to conditionally change the layout of some BuddyPress template page. If  we are on a single group page, for instance, I want a fullwidth layout. 

So, I've tried things like this 
```
add_filter( 'beans_layout', 'beans_child_bp_force_layout' );

function beans_child_bp_force_layout( $opt ) {
if ( bp_is_group_single() ) {
    $opt = 'c'; 
    return $opt;

    } 

}
```
But with no success. It changes the layout of the whole site.
Maybe my approach is a little bit naïve. Is there a solution ?

Mat

PS : I know that you can change the layout on a page-template basis, but this solution is not possible in BuddyPress (as far as I know). Plus, I think it's quite convenient to be able to change the layout of some sections of a website directly, in one place (functions.php, ideally), by adding some conditionnal tags to this snippet (http://www.getbeans.io/code-snippets/force-a-layout/).

**Comment by ThierryA** [comment]
Hi @Mat2012,

To apply the fullwidth content on single group view, the code would be as follow:

```
add_filter( 'beans_layout', 'beans_child_bp_force_layout' );

function beans_child_bp_force_layout( $layout ) {

	if ( bp_is_group_single() )
   		return 'c';

    return $layout;

}
```

Is that what you are looking for?

**Comment by Mat2012** [comment]
In one word : awesome !
Thanks a lot Thierry.
