### ISSUE TITLE
I am very intrigued...

### ISSUE THREAD

**Issue by paaljoachim** [Getbeans/Beans#2]
Hey Thierry

I came across the mention of your framework through WPMayors newsletter that lead me to http://wplift.com/beans-wordpress-theme-framework and the article intrigued. As well as your web site.

I use Genesis today. Some of the things I like with Genesis are:
- It is easy to change stuff through code snippets. Be it the comment phrases, meta etc..
- A lot of tutorials to find. I have also made a few. http://easywebdesigntutorials.com/Articles/wordpress/wordpress-themes/themes/
Tutorials such as: Adding breadcrumbs, adding widgets, creating a home page layout with widgets, back to top button, meta customization.

Some ideas:

- Here is a demo of a child theme made for Genesis:
https://secure.autopilotyourbusiness.com/genesischild/
The purpose here is to visually show widget areas for the child theme.

- Adding some screenshots to your docs will help.

Part 2.
I will download and do an initial test....
First thought where is the child theme which I found later inside the docs. I then installed both and activated the child theme. It seems like a good basic theme to start with. It would also be nice to add a customized child theme that includes custom CSS and a few more widgets. Perhaps something similar to the Genesis child them I linked to above. As one can have the bare bones basic theme and one with more information included.

Bare bones theme info. Then a custom theme info which could include these features: Multiple widget areas (top left and top right header, hero, home page widgets, after entry, footer header, etc), back to top button, a custom page menu (a conditional menu), a sticky header.

Part 3.
Test continues...
I added your sample hero widget area. I miss having a visual guide to the hook names.
I guessed and added an after markup widget area as well that showed up. I also tried adding a before header widget area did not show up.
I checked inspect element in Chrome and noticed the prefixes of tm and uk which made me wonder if your located in the UK because of the prefix. I do not know why the tm and uk prefixes though...

**Comment by ThierryA** [comment]
Hey Joachim,

Thanks for reaching out.

Part 2: 

The starter child theme can be found in the [Starter child theme article](http://www.getbeans.io/documentation/starter-child-theme/) article but I have made a note of your suggestion to add a link on the home page.
Regarding the child themes, we are still contemplating whether we should build official child themes or let third party contributors get their hands dirty.

Part 3:

Basically each markup in Beans has a hook before and after. Once you have enabled the dev mode in WordPress Admin->Settings->Beans, you will find a data-markup-id for each markup when inspecting the page. From there you can suffix it as such:

* **{$markup_id}_before_markup**, fires before the opening markup.
* **{$markup_id}_before_markup**{$markup_id}_prepend_markup</strong>, fires after the opening markup (not available for selfclosed markup).
* **{$markup_id}_before_markup**{$markup_id}_append_markup</strong>, fires before the closing markup (not available for selfclosed markup).
* **{$markup_id}_before_markup**{$markup_id}_afer_markup</strong>, fires after the closing markup.

You can then hook any callback functions to it, for instance outputting the hero widget area anywhere you would like to.

Regarding the classes prefix, all the ui- prefixed class are the [UIkit](http://getuikit.com/) and the tm- are the theme specific classes.

Thanks for your contribution,

**Comment by paaljoachim** [comment]
It would be great with some usage examples included in the docs in addition to the header widget which if I remember this right does something similar.
