### ISSUE TITLE
REM-version: UIKit + Beans

### ISSUE THREAD

**Issue by mixmode** [Getbeans/Beans#21]
Hi Thierry

I'd like to use Beans with (converted) rem-version of UIKit.
What is the best/cleanest strategy for overwriting of UIKit- and Beans-Styles?
Can i handle it complete in a child-theme, or is Beans modification unavoidable?

thanks
paul

**Comment by ThierryA** [comment]
Hi @mixmode,

UIkit is working on more rem orientated approach for version 3.0 but I am not 100% sure far they are with it. To overwrite UIkit and Beans, you can download and install the [starter child](http://www.getbeans.io/documentation/starter-child-theme/) theme and do your overwrites in it.

I would advise to use the `style.less` file as a ton of UIkit variables can be modified without having to overwrite CSS (and duplicate it). You may browse through the UIkit files in `tm-beans/lib/api/uikit/src/less`. You will see all the available variables on top of each file. All you have to do is add the variables your would like to modify in your child theme `style.less` and modify their values :)

Make sure you have dev mode enabled in Appearance->Settings for your changes to apply on the fly.

Happy coding,
