### ISSUE TITLE
Post gallery: no markup_id on the link and image

### ISSUE THREAD

**Issue by devignerforhire** [Getbeans/Beans#24]
I'm guessing that was by design, but it would really help if we were able to target the links and images. Some examples include using UIkits lightbox on the Gallery and setting uk-border-rounded on the image.

**Comment by ThierryA** [comment]
@devignerforhire the image is controlled by WP media for the gallery. You are welcome to use the markup id around the image or using the Core WP filters available (in `wp_get_attachment_image()` and `wp_get_attachment_link()` :-)

If you want to completely replace the image, you are welcome to use the beans_post_gallery_icon[_{$attachment_id}]_output filter to write your own. You have access to $image_output, $attachment_id, $atts parameters in the callback functions so you really have everything you need ;-)
