### ISSUE TITLE
Adding another sidebar layout - same as used in banks theme

### ISSUE THREAD

**Issue by paaljoachim** [Getbeans/Beans#245]
I have come across the not sure what to call it. 
Content in middle empty space on the left and right. Like a margin/padding on the left and right of the content. I have seen this used in a few themes and wondered why it was not included into the Beans core. In the below screenshot it shows the extra option in the customizer and to the right is shows how the content is pushed into the middle leaving space on the left and right. 

![screen shot 2018-06-14 at 22 58 14](https://user-images.githubusercontent.com/5323259/41438073-7afc03fa-7026-11e8-9e46-1ecaead62bb6.png)

https://github.com/ThemeButler/tbr-banks/blob/master/functions.php

**Comment by hellofromtonya** [comment]
Hey @paaljoachim, Did you get this resolved?  I saw @christophherr and you discussing it the other day on Slack.

**Comment by paaljoachim** [comment]
Hey @hellofromtonya. I never did get this resolved. It would be great if people can share their view points on this matter. Thanks.

**Comment by christophherr** [comment]
Personally, I think this is child theme territory.
The framework cannot account for all possible layout options.

I'm going to close this issue.
Please feel free to continue discussing here and/or reopening when there is more interest.

**Comment by paaljoachim** [comment]
Hey @christophherr 
I added a tutorial for it at wpbeansframework.com. 
It is fine to close it here.
