### ISSUE TITLE
Adding color options to the customizer?

### ISSUE THREAD

**Issue by paaljoachim** [Getbeans/Beans#247]
Today there is a color section in the customizer that adds a color to the background. (Actually the header and footer and not the content/main background.) Should we extend this? 

![screen shot 2018-06-16 at 16 24 42](https://user-images.githubusercontent.com/5323259/41499532-cec2bac2-7181-11e8-9ff5-57ee46f699f8.png)

**Comment by hellofromtonya** [comment]
Hello @paaljoachim, Hmm, I'm thinking that the "colors" section is something for the theme or site developer.  It seems to me that the theme author or site developer would want to only add controls here when it makes sense to give their clients more control of the look of the website.  For example, they may want to have different pre-configured branding set up where a person could select a red or blue or whatever theme option.  Or they want to give full style control to the client.  Others may want to lock it down to protect their client's custom branded site.

**Comment by paaljoachim** [comment]
Agreed. I will close this issue.
