### ISSUE TITLE
off-canvas menu

### ISSUE THREAD

**Issue by symmetrium** [Getbeans/Beans#25]
Hi Thierry

I have a quick support question about the off-canvas menu. When I click on the menu button nothing happens in my setup.
I did add my primary menu widget on the off-canvas menu area (Appearance > widgets), so it is not empty. I checked and it seems that the UIkit component is being loaded. Is there something I am missing for the off canvas menu to show? 

Thank you in advance ;)

**Comment by ThierryA** [comment]
Hey @symmetrium,

The primary menu is automatically added so you don't have to add menu widget. It is hard to say without seeing the page but the first which comes to my mind is a JS error preventing the off-canvas JS to work properly. Could you kindly post a link to the page if it isn't on a local environment?

Are you using a child theme and/or plugins. If yes does the issue still occur if you disable all plugins and and switch to Beans parent theme?

Thanks,

**Comment by symmetrium** [comment]
Hi! Thank you for your reply. 

I'm on a child theme. Switching to the parent theme had not helped. I will try disabling all the plugins and let you know. For the moment being I circumvented the problem by adding the following javascript to the site (which may point to a possible cause/solution?):

jQuery(document).ready(function($) { 
/* --- off-canvas menu --- */
	 $('a[href="#offcanvas_menu"]').click(function(){
	 	UIkit.offcanvas.show('#offcanvas_menu');
	 });
});

**Comment by ThierryA** [comment]
If that works it means that JS is working properly. Does your menu link have the `data-uk-offcanvas` attribute?

<img width="574" alt="screenshot 2016-01-05 13 37 41" src="https://cloud.githubusercontent.com/assets/3581402/12114322/8b4e8e6e-b3b1-11e5-83be-bfe9e2ce027d.png">

**Comment by symmetrium** [comment]
yes it does : )

**Comment by ThierryA** [comment]
Ok, the last thing I can think of off my head is that another even is conflicting. Have you tried to disable all plugins? If that doesn't help I will have to take a look at the code.

Kindly post the link to the page in that case :)

**Comment by ThierryA** [comment]
@symmetrium just a friendly reminder that we are awaiting for your reply ;)

**Comment by symmetrium** [comment]
Sorry for the delay, been real busy! 

The problem went way after disabling all plugins and re-enabling them all. Although I re-enabled them one by one, I could'nt identify which one was at the source of the problem.

I'll make sure to keep you posted if I find the culprit. 

Thanks a lot!
