### ISSUE TITLE
Establish repository for translation files

### ISSUE THREAD

**Issue by ibes** [Getbeans/Beans#258]
I am searching for a way to contribute to Beans and an easy thing I can do would be to make German translation.

It that a thing Beans should offer (I guess so as: why not?)?
Where should they be put? Is there already a good place for it?

**Comment by hellofromtonya** [comment]
Hello @ibes, we have been having conversations...briefly mind you, about how to handle translations for the Beans Community.

One idea is to create a GlotPress.  We have an open issue running where you can join and talk about it.  See issue #60.  We'd love to have your input.

**Comment by ibes** [comment]
Awesome - have not seen the issue. 
This can be closed - the other issue will already handle this.
