### ISSUE TITLE
Contributors Quick Start - npm not needed?

### ISSUE THREAD

**Issue by ibes** [Getbeans/Beans#259]
In the Contributors Quick Start: https://github.com/Getbeans/Beans/wiki/Contributors-Quick-Start

under headline: Setting Up Beans Development Version
there step 4
`npm install` is a step to do. 
But: There is no package.json in the repo - so it seems like this step is not there for good reason but likely a lost child from a maybe earlier version or the original project it was copied from. 

Am I right?

**Comment by hellofromtonya** [comment]
It's currently not needed.  However, we will be expanding to include more LESS, CSS, and JS tooling when we ramp into v2.0.0.  Then it'll be needed. :)

**Comment by ibes** [comment]
so take it out, let it in, add a comment that this step is not required in v1.x?

As it throws errors ("no package.json found") and inexperienced users won't know what to do about it, I feel like there should be something done with that

**Comment by hellofromtonya** [comment]
Done.  There are now notes that it's only for Beans 2.0.0.  Please check it out and let them know if that reads well and is clear.  Thanks :)

**Comment by ibes** [comment]
I guess there is no way to make it clearer. 
Awesome.

Just finished the tutorial and it's super straight forward and awesome :)

**Comment by hellofromtonya** [comment]
Thank you for pointing it out to me!  💯
