### ISSUE TITLE
Custom Post Type archive is not included in Breadcrumbs

### ISSUE THREAD

**Issue by kanishkkunal** [Getbeans/Beans#26]
For a custom post type, the breadcrumb does not include it's archive page. 
For e.g. I created a custom post type "WordPress Themes" and added a post called "Flipster" in it.
Now when I open the page Flipster the breadcrumb displays
**Home** > Flipster

<img width="97" alt="chrome_2016-01-21_15-47-41" src="https://cloud.githubusercontent.com/assets/2096152/12477574/4e0499ca-c056-11e5-905e-d5f56f11c8df.png">

Where as a better way to display the breadcrumb would be
**Home** > **WordPress Themes** > Flipster

<img width="160" alt="chrome_2016-01-21_15-48-21" src="https://cloud.githubusercontent.com/assets/2096152/12477589/63cd5080-c056-11e5-8113-00090f719a01.png">

Another problem is when I open the "WordPress Themes" archive page. I expect the breadcrumb to be 
**Home** > WordPress Themes
but it is just
**Home**

I digged into the code and also looked into the Breadcrumb output done by Yoast SEO plugin (which produces breadcrumb including the custom post's archive)

A custom post type doesn't have the archive page set as it's parent and therefore it doesn't get included with current code. Moreover the custom post type's archive page is not handled in the current breadcrumb's logic therefore we get an empty breadcrumb (except Home).

Is there any easy way to override/insert Custom Post Type archive in the breadcrumb? If not then what is recommended approach to fix this issue?

**Comment by ThierryA** [comment]
Hey @kanishkkunal, thanks for reporting it :)

I pushed the changes on the 1.3.0 [branch](https://github.com/Getbeans/Beans/commits/1.3.0) so you may pull and let me know how this work for you.

Thanks,

**Comment by kanishkkunal** [comment]
I can confirm that the breadcrumb output is exactly as expected for Custom Post Types with this change.
Thanks for super quick turnaround! :)

**Comment by ThierryA** [comment]
:+1:
