### ISSUE TITLE
Contributors Quick Start - fix maybe needed - remote vs upstream

### ISSUE THREAD

**Issue by ibes** [Getbeans/Beans#268]
Where: https://github.com/Getbeans/Beans/wiki/Git-Cheatsheet#keeping-your-branch-up-to-date

Step 1 

there it says:
`git pull remote development`

that maybe needs to be 
`git pull upstream development`
or
`git pull origin development`

as it is pull, I guess it needs to be upstream - so the official Beans repo.

**Comment by hellofromtonya** [comment]
Good catch.  Just updated to `upstream`.  Check it out to confirm.

**Comment by ibes** [comment]
confirmed - great.
