### ISSUE TITLE
Beans Layout Grid Settings: Allow Prefix configuration

### ISSUE THREAD

**Issue by kanishkkunal** [Getbeans/Beans#27]
Currently we can change the Beans layout grid using the following code snippet:

```php
beans_add_smart_action( 'beans_layout_grid_settings', 'beans_child_layout_grid_settings' );
function beans_child_layout_grid_settings( $layouts ) {

	return array_merge( $layouts, array(
		'grid' => 10,
		'sidebar_primary' => 3,
		'sidebar_secondary' => 3,
	) );
}
```

However the prefix for the grid is always `uk-width-medium`

It will be great if this prefix can also be configured, so that we can change it to say `uk-width-large`. This will be useful for themes which want to hide the sidebar on device-width smaller than 960px.

For e,g in theme for http://superdevresources.com/, I am manually doing the following to achieve this:
```php
if(beans_get_layout( ) != 'c') {
	beans_remove_attribute( 'beans_primary', 'class', 'uk-width-medium-7-10' );
	beans_add_attribute( 'beans_primary', 'class', 'uk-width-large-7-10' );
	beans_remove_attribute( 'beans_sidebar_primary', 'class', 'uk-width-medium-3-10' );
	beans_add_attribute( 'beans_sidebar_primary', 'class', 'uk-width-large-3-10 uk-visible-large' );
}
```

Currently it works as the layout is either c_sp or c. But if the layout is changed to something else say c_sp_ss then I will have to add extra checks and hence the code is not very maintainable in the long run. 

It will be much better to simply be able to specify `uk-width-large` as a param in `beans_layout_grid_settings`. Something like below:

```php
beans_add_smart_action( 'beans_layout_grid_settings', 'beans_child_layout_grid_settings' );
function beans_child_layout_grid_settings( $layouts ) {

	return array_merge( $layouts, array(
		'grid' => 10,
		'sidebar_primary' => 3,
		'sidebar_secondary' => 3,
		'prefix' => 'uk-width-large',
	) );
}
```

**Comment by ThierryA** [comment]
@kanishkkunal thanks for your feedback. I have added a new `breakpoint` argument to the `beans_layout_grid_settings` filter on the 1.3.0 [branch](https://github.com/Getbeans/Beans/commits/1.3.0) so you can do:

```
add_filter( 'beans_layout_grid_settings', 'beans_child_layout_grid_settings' );

function beans_child_layout_grid_settings( $layouts ) {

	return array_merge( $layouts, array(
		'grid' => 10,
		'sidebar_primary' => 3,
		'sidebar_secondary' => 3,
		'breakpoint' => 'large'
	) );

}
```

For information, and alternative would have been to use [`beans_replace_attribute()`](http://www.getbeans.io/code-reference/functions/beans_replace_attribute/) as follow:

```
beans_replace_attribute( 'beans_primary', 'class', 'medium', 'large' );
beans_replace_attribute( 'beans_sidebar_primary', 'class', 'medium', 'large' );
beans_replace_attribute( 'beans_secondary_primary', 'class', 'medium', 'large' );
```

Note that you don't have to do any layout check as it would work on any layout. When using [`beans_replace_attribute()`](http://www.getbeans.io/code-reference/functions/beans_replace_attribute/), you may only replace a part of an attribute. Be aware that if multiple attribute contain the same string it would replace all instances which can be unwanted sometimes.

Thanks,

**Comment by kanishkkunal** [comment]
Thanks @ThierryA for the update.
Replacing only part of the attribute surely would have been a much better option. Thanks for the Tip!
