### ISSUE TITLE
GDPR Compliance

### ISSUE THREAD

**Issue by ibes** [Getbeans/Beans#274]
Maybe you heard of the new European data protection law.
At least in Germany that was a big deal and will stay a big deal from now on. 

A WP theme and Beans should not have any need to take care of GDPR, I guess. 
Or are there things we should take care of?

Are there resets that make sense, like stop cookies from being set, pings to be unset etc.

Oh - comments should be saved without IP address. 

Maybe there are ground work tasks that could be done in the theme or as a plugin. 

Would be great if the combination of Core and Beans would already be a clean state.

**Comment by hellofromtonya** [comment]
I can't think of any issues within the framework that would need GDPR attention.  @christophherr can you?

**Comment by christophherr** [comment]
@hellofromtonya
No, the things mentioned here are handled by WP core. 

It doesn't look like updater.php is sending any "identifiable" information (IP address, site name,...) back to the update server, is that right? And even if, it would be more an issue of adding that to a Privacy Policy on the website.

**Comment by hellofromtonya** [comment]
Cool thank you @christophherr.  

Hey @ibes, thank you for opening the discussion for us to review.  I'll go ahead and close this issue as it does not apply to Beans.
