### ISSUE TITLE
Remove query strings

### ISSUE THREAD

**Issue by yoneth** [Getbeans/Beans#29]
I tested my site with gtmetrix, I've got an 'F' grade :
"Resources with a "?" in the URL are not cached by some proxy caching servers. "

How do I remove it in Beans ?

**Comment by ThierryA** [comment]
Hey @yoneth, do you have a link to your site? Make sure you disable dev mode in Appearance->Settings and enable assets compiling options.

Thanks,

**Comment by yoneth** [comment]
Here you go : http://bit.ly/leadmatic

**Comment by ThierryA** [comment]
It doesn't look like the compiling options are checked in Appearance->Settings.

**Comment by yoneth** [comment]
I've just checked both 'Compiles WP styles' and 'Compiles WP scripts' , and I still got an F grade ( eventhough it earns few points )

**Comment by ThierryA** [comment]
I see compiling options are enabled now, the appended query string seems to be still there, do you have any plugins installed?

**Comment by yoneth** [comment]
I have W3 total cache plugin activated. 

I have deactivated all plugins. And now I've got a 'D' grade, these are the remaining query strings
`.../wp-includes/js/wp-embed.min.js?ver=4.4.2
.../wp-includes/js/wp-emoji-release.min.js?ver=4.4.2
`


Thank you for your help.

**Comment by ThierryA** [comment]
You can remove the emoji as below if you don't use it:

`remove_action( 'wp_print_styles', 'print_emoji_styles' );`

Alternatively, you can remove all query strings as follow:

```
add_filter( 'script_loader_src', '_remove_script_version', 15 );
add_filter( 'style_loader_src', '_remove_script_version', 15 );

function _remove_script_version( $src ){

	$parts = explode( '?', $src );

	return $parts[0];
	
}
```

**Comment by yoneth** [comment]
Superb. Thank you!

**Comment by ThierryA** [comment]
My pleasure :+1:
