### ISSUE TITLE
v1.5.0-beta: Customizer does not reflect tm-logo updates in its preview.

### ISSUE THREAD

**Issue by paaljoachim** [Getbeans/Beans#293]
Hey

I tried to break something and I did....

I installed the beta through Desktop Server. I am using Chrome.

In the customizer. I adjusted the color. Then I added a large logo image, a large header image and then a background image. Went back to change the header image. Then removed the logo. 
See the below screenshot.

![screen shot 2018-06-26 at 14 39 30](https://user-images.githubusercontent.com/5323259/41912064-c860cee2-794e-11e8-9cef-71e079590927.png)

Btw exiting the customizer and then going back again the logo in the top was now gone.
So it just might be one of the the local site customizer ghosts...

**Comment by paaljoachim** [comment]
I removed the logo image from the logo Image area in the Customizer, but it still remains in the preview. Even though I click publish it is still there. Viewing the site outside of the Customizer the logo is gone.

**Comment by ibes** [comment]
What happens if you go back to Preview / Customizer?

**Comment by paaljoachim** [comment]
It is then gone..:)

**Comment by ibes** [comment]
Just trying to figure out what is done there. 

Customizer information is - as far as my search is right - stored in the options table in a field titled 
`theme_mods_THEMENAME`, where "THEMENAME" is the slug of the theme. 

Site logo and background etc. should be a function that comes from WP core and is - by activate theme_support - just used by Beans.

All the output of background, logo etc. happens in the tm-beans/lib/templates/fragments/header.php

That uses WP core's get_header_image(); (obviously: header image)
get_theme_mod( 'beans_logo_image', false ); (the logo)

Oh - beans_logo_image is a custom thing. 

Defined as (cut out code that doesn't seem to be important for the logo):
```PHP
function beans_do_register_wp_customize_options() {
	$fields = array(
		array(
			'id'    => 'beans_logo_image',
			'label' => __( 'Logo Image', 'tm-beans' ),
			'type'  => 'WP_Customize_Image_Control',
		),
	);

	beans_register_wp_customize_options( $fields, 'title_tagline', array( 'title' => __( 'Branding', 'tm-beans' ) ) );

 ...
}
```
located at: tm-beans/lib/admin/wp-customize.php

**Comment by ibes** [comment]
so sounds like the refresh trigger is maybe off place. 

Could you validate, that this is not a general WP bug?
Could you test with the standard themes? twentysomething?

**Comment by paaljoachim** [comment]
I am testing with Twenty Sixteen and Twenty Seventeen there adding Logo Image and then removing it again works. Then switch back to the Beans theme again and it is stuck.

Ok there seems to be a bug present with adding Logo Image and then removing it again. It stays stuck.

**Comment by ibes** [comment]
I am not experienced with Customizer and I guess can't efficiently dig deeper from here. 
But sounds like we have a quite concrete situation. 

Customizer doesn't reflect tm-logo updates in its preview. 

Seems like the live site does the change without trouble - the problem is somewhere in the Customizer handling.

**Comment by christophherr** [comment]
Confirming this is a regression in 1.5. 
Thank you for testing and finding a bug @paaljoachim 🥇 
We changed the default transport method in `class-beans-wp-customize.php` to `postMessage` ( for the preview tools).

**Comment by ibes** [comment]
Woop.
Awesome team work. 

And also from me an award to @paaljoachim for (trying to) break things.
