### ISSUE TITLE
Styling for the new "Comment Forms Cookies Consent" feature

### ISSUE THREAD

**Issue by christophherr** [Getbeans/Beans#297]
Checkbox and label look a bit too close.

![comment-form](https://user-images.githubusercontent.com/8683126/42191535-5886d71e-7e31-11e8-981b-4195c72138dd.png)

And the new `<fieldset>` element (the comment-form) could use a bit of padding-bottom.

**Comment by hellofromtonya** [comment]
@christophherr Did you want to do a PR for this and include it in the Beans v1.5 release?

**Comment by hellofromtonya** [comment]
Or maybe you could work with @ibes on this one?

**Comment by ibes** [comment]
Sorry - my to do list is killing me right now. 
I guess that could be a good task for me, but better assign it to someone else. 
If I get to be the master of my to do list again I can come back and grab it, if it is still open ;)

**Comment by christophherr** [comment]
Thank you for letting us know, @ibes.
