### ISSUE TITLE
Problem with js compiler

### ISSUE THREAD

**Issue by yoneth** [Getbeans/Beans#30]
I add this function under child theme 

    add_action( 'wp_enqueue_scripts', 'compile_js' );

    function compile_js() {
	    beans_compile_js_fragments( 'js_compiler', ('/wp-content/themes/beans-child/custom.js') );
    }

The problem is , the output has `;` character in the beginning of the file. You can see it [here](http://lead-matic.com/wp-content/uploads/beans/compiler/js_compiler/52ed18e.js)

How do I get rid of it ?

Thanks

**Comment by ThierryA** [comment]
@yoneth the `;` is actually added as a safety major and should not cause any JS issues. What error are you actually getting?

That said the way the compiler as evolved I think we could remove it. I have added it to the list of tasks and will do testing before removing it.

**Comment by yoneth** [comment]
I was trying to add `uk-button` class into the button tag using jQuery.

`jQuery('.button').addClass('uk-button uk-button-primary');`

It worked when executed using chrome console, but it did not work when compiled.

Do you have any idea ?

**Comment by ThierryA** [comment]
I just checked http://lead-matic.com/ which is loading fine with the compiled js_compiler, could you add an html a tag with the `.button` class in the content to test it?

Make sure you clear the assets cache in Appearance->Settings when you disable dev mode. If you don't want a new compiler file to be created, you may do ` beans_compile_js_fragments( 'uikit', ('/wp-content/themes/beans-child/custom.js') );` to add your JS in the UIkit compiled file.

**Comment by yoneth** [comment]
I have added a button to test in the homepage.

**Comment by ThierryA** [comment]
I think the problem there is that it fires before the document is ready actually. Try the following:

```
( function( $ )  {
	$( document ).ready( function() {
		 $( '.button' ).addClass( 'uk-button uk-button-primary' );
	} );
} )( jQuery );
```

**Comment by yoneth** [comment]
It worked. Thank you for your prompt response!

**Comment by ThierryA** [comment]
My pleasure :+1:
