### ISSUE TITLE
Default input wrap class in comment form

### ISSUE THREAD

**Issue by MatRouault** [Getbeans/Beans#301]
Hello,

In the comment form, wouldn't it be better to have
```
beans_comment_form[_name]
beans_comment_form[_email]
beans_comment_form[_website]
```
wrapped by default in a `uk-width-medium-1-3` class rather than `uk-width-medium-1-4` ?

Currently

![screen-1](https://user-images.githubusercontent.com/1023932/42513862-4c7e42fe-8458-11e8-844b-b42d04ba9f23.png)

After

![screen-2](https://user-images.githubusercontent.com/1023932/42513895-6336db64-8458-11e8-9a2a-2ddd04185708.png)

Of course it is not an "issue", since it can be changed via Beans Markup API.

Thanks for the huge work ! :-)

**Comment by ibes** [comment]
Are you on the newest version on Beans 1.5?
There was a ticket about the comment section which might already has catched this. 

Found the ticket: 
https://github.com/Getbeans/Beans/issues/297

Seems to be about something else. 

Definitely the second screenshot / variation looks more appealing.

**Comment by MatRouault** [comment]
Yes @ibes I'm currently tring the RC. The ticket you mentionned does not resolve this - very little and only esthetical - problem.

**Comment by hellofromtonya** [comment]
Thank you, @MatRouault.  I think this is a good idea and one that we can roll into our next release, i.e. Beans 1.6.  Would you be interested in submitting a PR for it?

**Comment by Tsquare17** [comment]
I'm can't seem to replicate this issue. The comment input fields are wrapped by default with `uk-width-medium-1-3` on a fresh installation.
![screenshot_2018-10-13 hello world beans](https://user-images.githubusercontent.com/19720119/46906888-6c4c5600-ced8-11e8-90b2-239a49584968.png)

**Comment by christophherr** [comment]
Hi @Tsquare17,
Thanks for checking.

Hmm... I don't know what happened here.
The grid class is automatically applied depending on the number of fields:
`$grid      = count( (array) $fields );`
and 
`$author = beans_open_markup( 'beans_comment_form[_name]', 'div', array( 'class' => "uk-width-medium-1-$grid" ) );`

There might have been a hidden field. 

@MatRouault I'm closing this for now. 
Please feel free to re-open if this is still happening ( and maybe add a screenshot of the dev tools / HTML markup).

**Comment by MatRouault** [comment]
Can't reply this error anymore...

**Comment by christophherr** [comment]
Thank you for confirming 👍
