### ISSUE TITLE
All In One WP Security plugin removes file permissions from screenshot.jpg and Beans updates fail

### ISSUE THREAD

**Issue by paaljoachim** [Getbeans/Beans#304]
I tried to update Beans 1.4 to 1.5 for a Norwegian culture house site that I run.

In the updates screen:

Notice the missing image thumbnail.

![screen shot 2018-07-17 at 01 46 10](https://user-images.githubusercontent.com/5323259/42789050-507df5f6-8963-11e8-8f42-bd6ef68c49b8.png)

As it updates the Beans theme it goes through the steps and ends up with a failed update.
An error happened when Beans was updated: Update can not be installed because some of the files could not be copied. This is likely because of inconsequent file permissions. screenshot.jpg.

--

I turned off a few of the plugins to see if that would work but it did not.
I switched to Twenty Seventeen and then tried to update through the Appearance -> Theme tab and it showed me this:

![screen shot 2018-07-17 at 02 00 26](https://user-images.githubusercontent.com/5323259/42789364-3b256868-8965-11e8-85af-312a3d987e6e.png)

Btw as I switched to another theme and then back again I lost one of the widgets in the footer area and had to reinsert it.
(Using this code: https://wpbeansframework.com/2018/05/31/how-to-add-3-widget-area-in-one-place/ )

If someone would like to take a look let me know and I will give you login information to the Norwegian site.

**Comment by hellofromtonya** [comment]
Hello @paaljoachim, Hmm, I'm wondering if the host is blocking it.  I just ran through an update on a couple of my sites to make sure the update service is working.  And yes, it worked.  

Have you had issues in the past with updating this client/site?

Another approach is to SFTP or SSH into the site to do the update that way.

**Comment by paaljoachim** [comment]
I chatted with the host support and they fixed the permission error. They do not know why it happened.

Here is the message I received through Duplicator before the fix.

PHP is unable to read the following items and they will not be included in the package. Please work with your host to adjust the permissions or resolve the symbolic-link(s) shown in the lists below. If these items are not needed then this notice can be ignored.

[13:46:58]
Paal Joachim: /home/stabestr/public_html/wp-content/themes/tm-beans/screenshot.jpg

I will close this for now as I got this fixed.

**Comment by paaljoachim** [comment]
I have now a dev site in place from before upgrading to Beans 1.5.
For whatever reason the screenshot had permission problems that the host reset.
Beans 1.5 also mocked up the shortcodes I used from Eventon event plugin.

**Comment by hellofromtonya** [comment]
I've not been able to recreate this issue.  Hey @christophherr, can you see if you can recreate it on your machine?  

>Beans 1.5 also did something with the shortcodes I used from Eventon event plugin so that the front page did not show up as it should.

@paaljoachim this would be a separate issue.  Can you open a new one please?

**Comment by christophherr** [comment]
I cannot recreate the issue. 
@paaljoachim Any chance that permissions had been changed in the past?
Might have been for security reasons. ( I think in some "black market" themes and plugins, "image files" were used to disguise and spread malicious code...)

**Comment by paaljoachim** [comment]
@christophherr I sent you a pm through slack with login info so that you can take a look.

**Comment by christophherr** [comment]
The All In One WP Security plugin is removing the file permissions from `screenshot.jpg` and variations of that filename. 

@hellofromtonya Is there a reason we are using a `.jpg` instead of the [standard `.png`](https://developer.wordpress.org/themes/release/required-theme-files/)?

**Comment by hellofromtonya** [comment]
@christophherr PR #311 adds a newly designed screenshot that is in PNG format.  This should close this issue.
