### ISSUE TITLE
Less is not compiled "on the fly" in development mode

### ISSUE THREAD

**Issue by christophherr** [Getbeans/Beans#307]
Adding from the forum: https://community.getbeans.io/discussion/compiler-not-disabled-in-development-mode/

> I put the theme in development mode under appearance > settings. However each time I make a change in the CSS it still requires me to flush the cache assets for the change to show on screen. I am currently using Beans 1.5.0.
https://community.getbeans.io/discussion/compiler-not-disabled-in-development-mode/#post-4687
As far as I could figure out, the issue comes from line 687 of the _Beans_Compiler class (\tm-beans\lib\api\compiler\class-beans-compiler.php):
`if ( file_exists( $fragment ) )`
If you are using the starter child theme as a base for your child theme, you probably have a line in your functions.php along the lines of
`beans_compiler_add_fragment( 'uikit', get_stylesheet_directory_uri() . '/style.less', 'less' );`
As far as I can tell, all these fragments are passed to the Beans Compiler when it is constructed, and if your child theme is set up as assumed, the fragment is stored with reference to its URL. When the compiler gets to the previously mentioned if statement, it'll be checking file_exists with a URL, while it seems to need a local path to work (if passed a URL it always returns false, therefore skipping the next lines, which would change the modification time, which in turn is needed when computing the new hash to see if the file has been changed).

**Comment by hellofromtonya** [comment]
@christophherr is this a regression issue as introduced in 1.5.0?  Or has it been there previously?

**Comment by christophherr** [comment]
@hellofromtonya 
It sounds like a regression from the two posts on the forum. I haven't tested.
