### ISSUE TITLE
Beans 1.5 - Compiler breaks IE 6-9 style filter:progid:DXImageTransform.Microsoft.Gradient

### ISSUE THREAD

**Issue by paaljoachim** [Getbeans/Beans#309]
Hey

After the host reset the permission for the screenshot image file able I was then able to upgrade to version 1.5. I noticed that the Eventon plugin shortcodes were not showing correctly after the upgrade. I had to go back to 1.4 on the main site.  I made a dev site: https://stabekkino.no/dev

 @christophherr has the login info to the site.

**Comment by christophherr** [comment]
@hellofromtonya 
This looks like a compiler issue. 
When styles are compiled the layout breaks, i.e. classes that are in the stylesheet are not applied. 
Beans 1.4 compiled styles: 
![working-styles-beans-1 4](https://user-images.githubusercontent.com/8683126/43041051-01b92490-8d23-11e8-8b87-86b36adb6e47.png)

Beans 1.5 compiled styles:
![broken-styles-beans-1 5](https://user-images.githubusercontent.com/8683126/43041055-1321b85a-8d23-11e8-9211-ed26241cd814.png)

Beans 1.5 un-compiled styles:
![beans-1 5-not-compiling-styles](https://user-images.githubusercontent.com/8683126/43041076-69a5d0e4-8d23-11e8-8c53-1d6da81ea41e.png)

1.4 and 1.5 compiled styles have almost identical errors in the validator. 
The difference in line numbers comes from closing braces not being on their own line in 1.5.
Beans 1.4 style sheet:
[beans1.4styles.txt](https://github.com/Getbeans/Beans/files/2216623/beans1.4styles.txt)
Beans 1.5 style sheet:
[beans1.5styles.txt](https://github.com/Getbeans/Beans/files/2216624/beans1.5styles.txt)

**Comment by christophherr** [comment]
This is the selector causing the trouble:
`.evcal_event_details .evcal_evdata_cell .eventon_details_shading_bot`

Line 1608 in eventon_styles.css:
```[css]
.evcal_event_details .evcal_evdata_cell .eventon_details_shading_bot{
	background: -moz-linear-gradient(top,  rgba(245,245,245,0) 0%, rgba(245,245,245,0.01) 1%, rgba(245,245,245,1) 100%); /* FF3.6+ */
	background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(245,245,245,0)), color-stop(1%,rgba(245,245,245,0.01)), color-stop(100%,rgba(245,245,245,1))); /* Chrome,Safari4+ */
	background: -webkit-linear-gradient(top,  rgba(245,245,2454,0) 0%,rgba(245,245,245,0.01) 1%,rgba(245,245,245,1) 100%); /* Chrome10+,Safari5.1+ */
	background: -o-linear-gradient(top,  rgba(245,245,245,0) 0%,rgba(245,245,245,0.01) 1%,rgba(245,245,245,1) 100%); /* Opera 11.10+ */
	background: -ms-linear-gradient(top,  rgba(245,245,245,0) 0%,rgba(245,245,245,0.01) 1%,rgba(245,245,245,1) 100%); /* IE10+ */
	background: linear-gradient(to bottom,  rgba(245,245,245,0) 0%,rgba(245,245,245,0.01) 1%,rgba(245,245,245,1) 100%); /* W3C */
	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#00{$_grad_hex}', endColorstr='#{$_grad_hex}',GradientType=0 ); /* IE6-9 */
	position:absolute;
	bottom:0; left:0;
	/*background:url(../images/more_details_fade_bg.png) top left repeat-x;*/
	height:60px;
	width:100%;
	z-index: 1;
}
```

Beans 1.4 compiled version:
```[css]
.evcal_event_details .evcal_evdata_cell .eventon_details_shading_bot{background:-moz-linear-gradient(top,rgba(245,245,245,0) 0%,rgba(245,245,245,0.01) 1%,rgba(245,245,245,1) 100%);background:-webkit-gradient(linear,left top,left bottom,color-stop(0%,rgba(245,245,245,0)),color-stop(1%,rgba(245,245,245,0.01)),color-stop(100%,rgba(245,245,245,1)));background:-webkit-linear-gradient(top,rgba(245,245,2454,0) 0%,rgba(245,245,245,0.01) 1%,rgba(245,245,245,1) 100%);background:-o-linear-gradient(top,rgba(245,245,245,0) 0%,rgba(245,245,245,0.01) 1%,rgba(245,245,245,1) 100%);background:-ms-linear-gradient(top,rgba(245,245,245,0) 0%,rgba(245,245,245,0.01) 1%,rgba(245,245,245,1) 100%);background:linear-gradient(to bottom,rgba(245,245,245,0) 0%,rgba(245,245,245,0.01) 1%,rgba(245,245,245,1) 100%);filter:progid:DXImageTransform.Microsoft.gradient( startColorstr='#00{$_grad_hex}',endColorstr='#{$_grad_hex}',GradientType=0 );position:absolute;bottom:0;left:0;height:60px;width:100%;z-index:1}
```

Beans 1.5 compiled version:
```[css]
.evcal_event_details .evcal_evdata_cell .eventon_details_shading_bot{background:-moz-linear-gradient(top,rgba(245,245,245,0) 0%,rgba(245,245,245,0.01) 1%,rgba(245,245,245,1) 100%);background:-webkit-gradient(linear,left top,left bottom,color-stop(0%,rgba(245,245,245,0)),color-stop(1%,rgba(245,245,245,0.01)),color-stop(100%,rgba(245,245,245,1)));background:-webkit-linear-gradient(top,rgba(245,245,2454,0) 0%,rgba(245,245,245,0.01) 1%,rgba(245,245,245,1) 100%);background:-o-linear-gradient(top,rgba(245,245,245,0) 0%,rgba(245,245,245,0.01) 1%,rgba(245,245,245,1) 100%);background:-ms-linear-gradient(top,rgba(245,245,245,0) 0%,rgba(245,245,245,0.01) 1%,rgba(245,245,245,1) 100%);background:linear-gradient(to bottom,rgba(245,245,245,0) 0%,rgba(245,245,245,0.01) 1%,rgba(245,245,245,1) 100%);filter:progid:DXImageTransform.Microsoft.gradient( startColorstr='#00{$_grad_hex}
',endColorstr='#{$_grad_hex}
',GradientType=0 );position:absolute;bottom:0;left:0;height:60px;width:100%;z-index:1}
```

**Comment by christophherr** [comment]
Here is a possible fix: 
https://github.com/christophherr/Beans/tree/replace
https://github.com/Getbeans/Beans/compare/development...christophherr:replace

The result can be seen on Paal's dev site: https://stabekkino.no/dev/

**Comment by hellofromtonya** [comment]
@christophherr The Compiler is breaking it up because `}` is not within a CSS style declaration.  Rather, it indicates the end of a style block declaration.

>That's CSS from the eventon plugin.

Then I'd advise contacting the plugin author and having him/her fix the invalid CSS issue as noted above.

**Comment by hellofromtonya** [comment]
@paaljoachim The eventon plugin has invalid CSS in it as noted above. It's invalid in the previous version of Beans too.  The difference between it and the latest version of Beans 1.5 is that we now do a line break on each CSS ending curly brace.  Because the eventon plugin's CSS is invalid, it has extra ending curly braces in it.

I want to give you some helpful suggestions.  You can pick your course of action:

1. Contact the plugin author and ask him/her to fix the invalid CSS.
2. In the meantime until s/he fixes it, you can use Beans 1.4 as you were before _or_ use Beans 1.5 but don't compile the CSS.

Another option is to switch to a different plugin than the eventon one.

**Comment by hellofromtonya** [comment]
@christophherr Thank you for spending time on this issue.  I really appreciate your hard work.

This issue is not a Beans issue.  Rather, it's an invalid CSS in a plugin.

@paaljoachim I'm closing this issue.

**Comment by paaljoachim** [comment]
Thank you very much for pinning the issue on this Tonya and Christoph!
I will contact the developer in regards to this issue.
