### ISSUE TITLE
Preview Tools not need anymore

### ISSUE THREAD

**Issue by bdthemes** [Getbeans/Beans#31]
Hello, thanks for the beans theme. i am so happy with it. i think "Preview Tools" in customizer not need anymore. because wordpress added responsive checking button at bottom.

**Comment by ThierryA** [comment]
Thanks for your feedback @bdthemes. The new WP Viewport Tool is great but they are only 3 pre-define views while Beans Preview Tool is a lot more precise. For that reason we will keep it but you are welcome to remove it using the following filter if you don't want to use it:

```
add_filter( 'beans_wp_customize_fields_beans_preview', '__return_empty_array' );
```

Thanks,

**Comment by bdthemes** [comment]
Ok, thanks
