### ISSUE TITLE
Licensing Issue for professional template

### ISSUE THREAD

**Issue by bdthemes** [Getbeans/Beans#32]
Hello,

i am a theme developer. i am selling my theme on themeforest. i want to move from others framework to beans theme and want to develop theme with beans. but there are a problem with license. you told it's free but there are not included any license reference such as GPL or MIT or something else.

if you want to give it free to us so can you add GPL license at top of all files? if you not add license i can't use it for professional theme. 

example license:

```
/**
* @package   Beans
* @author    Beans http://www.getbeans.io/
* @copyright Copyright (C) Beans
* @license   http://www.gnu.org/licenses/gpl.html GNU/GPL
*/
```

**Comment by ThierryA** [comment]
@bdthemes [here is the license declaration](https://github.com/Getbeans/Beans/blob/development/style.css#L10), it does not need to be added in all files, as you will also notice in WP Core themes.

GPL it is, and will always be ;-)

**Comment by bdthemes** [comment]
Thanks for clarification :)
