### ISSUE TITLE
Customizer: Background thumbnail image disappears on return.

### ISSUE THREAD

**Issue by paaljoachim** [Getbeans/Beans#321]
Hey

Beans version 1.5.1.

This is similar to the fixed image logo issue here: https://github.com/Getbeans/Beans/issues/293

Go into the Customizer -> Background image -> Select image.
Exit.
Go back into the Customizer -> Background image ---- no image seen.
See screenshot:

![screen shot 2018-08-13 at 15 19 06](https://user-images.githubusercontent.com/5323259/44033988-527d339e-9f0c-11e8-8a7d-51c1e615e9d1.png)

Btw
I just checked the Header Image Customizer section. The thumbnails remains seen also after exit and return to the Customizer.

**Comment by christophherr** [comment]
If you exit after selecting the image, you forgot to publish your changes.

**Comment by paaljoachim** [comment]
Here is a gif:

![beans-customizer-background-image](https://user-images.githubusercontent.com/5323259/44041672-a5d14ca8-9f1e-11e8-9e19-272632d2f1ec.gif)

I am using 
Desktop Server.
Chrome

Activated plugins:
Autoptimize

No deactivated plugins.

**Comment by christophherr** [comment]
I can't reproduce this (I am not using desktop server).

Beans does not modify the Core feature (custom-background).

**Comment by paaljoachim** [comment]
I tested this on one of my online sites and the preview image is still there, so I am closing this issue as it seems to only have relevance to offline sites using Desktop Server.
