### ISSUE TITLE
Old draft is published using todays date. Does not show up on top of the blog page.

### ISSUE THREAD

**Issue by paaljoachim** [Getbeans/Beans#322]
I have a few older drafts. I took one of them today "Full screen background image" at https://wpbeansframework.com/ and made a tutorial that I published.

Usually new posts are seen at the top of the blog page but publishing older drafts they will show in the order on the blog page of the draft time stamp they originally were created. Even though it changed to: Published on: Aug 13, 2018 @ 15:19 it shows up further down on the page. 

So it seems that somehow the post sticks to the original draft date and does not update to the publish date. Even though the publish date is seen above the post on the front page.
https://wpbeansframework.com/

![screen shot 2018-08-13 at 17 52 24](https://user-images.githubusercontent.com/5323259/44042862-b08f6d52-9f21-11e8-8936-56d81e7abd4b.png)

----

I have noticed this a few times. If I want this tutorial to show up on top of the blog page I have to create a new post and do a copy and paste of the content from the draft -> published post. Then it will show as the first post.

**Comment by ibes** [comment]
Are you sure that is a Beans issue or can it be a WordPress/expectation issue. 

Posts in the archives are ordered by date. 
Should be the publication date. 
But I don't know what that date is on drafts. 

I guess I too would expect that drafts are ordered by the date they enter "publish" as post_status.

**Comment by paaljoachim** [comment]
Hey Ibes..:)

Draft shows no visible time or date. Publish does.
But it seems like somehow the hidden draft time and date overwrites the publish dates. 

I am thinking that the timestamp in some way retains the original (draft mode) time  even though it is hidden. That the timestamp is not refreshed on publish.

**Comment by christophherr** [comment]
Hey @paaljoachim,
I know you redesigned the website but do you still have the code that resulted in this problem?
Did you schedule the posts with Calypso or one of the mobile apps?

**Comment by paaljoachim** [comment]
Hey @christophherr 

I made a backup with duplicator that has the issue.
I did not use Calypso or any mobile app.

Btw
I just logged into the new site and published one of the drafts I had from a few days ago. It showed up first in the blog list. 

So I am going to close this issue for now, and if it the problem shows up again then I can always reopen this issue.

**Comment by christophherr** [comment]
Thank you, @paaljoachim.
