### ISSUE TITLE
typo? -> beans_uikit_euqueued_styles

### ISSUE THREAD

**Issue by ibes** [Getbeans/Beans#323]
In this file there are four times the word: `euqueued`

eg. in `beans_uikit_euqueued_styles` in: 
https://github.com/Getbeans/Beans/blob/development/lib/api/uikit/class-beans-uikit.php#L62

Is this a typo or a thing that is just unfamiliar to me?

as it is easy to overread as "u" and "n" are kind of the same thing here again:

e**U**queued

**Comment by christophherr** [comment]
It's a typo.
See https://github.com/Getbeans/Beans/pull/253#discussion_r196625438
for details why we did not change it.

**Comment by ibes** [comment]
I see :)
