### ISSUE TITLE
Composer.json / Roave/SecurityAdvisories / master

### ISSUE THREAD

**Issue by ibes** [Getbeans/Beans#324]
I would like to require Beans through composer. 
As the type is set correctly to "wordpress-theme" that would be possible with my setup. 
(Tutorial about this is already written - if you are interested ...)

BUT
Beans required Roave/SecurityAdvisories in the requirements for using the project.
https://github.com/Getbeans/Beans/blob/master/composer.json#L41
 
In the Repo itself it says it is a dev-requirement: https://github.com/Roave/SecurityAdvisories

Roave/SecurityAdvisories will never be stable - so to require Beans I need to lower my "minimum-stability": "dev",
That feels like a downgrade in security and stability. 

Am I right that Roave/SecurityAdvisories is in the wrong requirement block?

**Comment by christophherr** [comment]
It's corrected in the development branch. https://github.com/Getbeans/Beans/blob/development/composer.json#L48

Master will be updated with the next Beans release.

**Comment by ibes** [comment]
looking forward to this - will makes things a lot more comfortable
