### ISSUE TITLE
Proposal for the "code snippet" section of the website

### ISSUE THREAD

**Issue by ibes** [Getbeans/Beans#326]
I don't like Customizer and want as much stuff as possible in code. 

So I set the website logo via code while still taking use of Beans to handle it.

Is there another action that could be better suited?

```PHP
// set logo programmatically
add_action( 'after_setup_theme', 'mytheme_set_logo' );
function mytheme_set_logo() {
    set_theme_mod('beans_logo_image', get_stylesheet_directory_uri() . '/assets/images/logo.png');
}
```

**Comment by christophherr** [comment]
@ibes 
The hook is fine and this should also work after https://github.com/Getbeans/Beans/issues/295 is done.
