### ISSUE TITLE
Less compiler errors.

### ISSUE THREAD

**Issue by Pross** [Getbeans/Beans#329]
If the lessc class is included by a plugin before the theme inits then you get a lessc_parser class already defined fatal error. 
Although Lessc class is namespaced whoever did it forgot to namespace the other classes in that file, easy oversight.
PR incomming.

**Comment by christophherr** [comment]
Hey @Pross,
Thank you for opening the issue and the pull request.
I just want to compare our version of Lessphp with the latest version on their repo before merging.
