### ISSUE TITLE
Auto update of copyright year

### ISSUE THREAD

**Issue by paaljoachim** [Getbeans/Beans#34]
Hey Thierry

It would be good to have somekind (shortcode perhaps) to auto update copyright year.
So that one does not need to go back to every site and update year.

**Comment by ThierryA** [comment]
Hey @paaljoachim,

The copyright year is automated as you can [see here](https://github.com/Getbeans/Beans/blob/development/lib/templates/fragments/footer.php#L25).

PS: themes should not contain shortcode according to wordpress.org requirements.

**Comment by paaljoachim** [comment]
Great! I just posted about this in the forums as well.
Have a great day!
