### ISSUE TITLE
Gaining access to a Duplicator backup of the Get Beans web site

### ISSUE THREAD

**Issue by paaljoachim** [Getbeans/Beans#346]
It would be very helpful if I could get a hold of a Duplicator Backup of the Get Beans web site.
1. I would then be able to extract the bbPress code in use. (To create a tutorial.)
2. Check out closer how things are put together plugins and the theme.
3. Extract additional Beans code that I can use for a tutorial.

Thanks.

**Comment by christophherr** [comment]
I know your heart is in the right place. 
We cannot and will not give out information like this.
