### ISSUE TITLE
Editing forum post resets back to General forum

### ISSUE THREAD

**Issue by paaljoachim** [Getbeans/Beans#35]
Hey

As I edit my post in the Support forum it automatically jumps back to General.
So I have had to a few times edit my post again to switch it back to the correct forum.

**Comment by ThierryA** [comment]
Thanks for reporting that, I will look into it.

PS: Please keep in mind that Github issues are only meant to report Beans potential bugs, the forum isn't related to Beans code.

**Comment by paaljoachim** [comment]
Ok. I'll post stuff that is in the grey zone on the forum and you can see whenever you see it.
