### ISSUE TITLE
Editor style - a long h1 title

### ISSUE THREAD

**Issue by paaljoachim** [Getbeans/Beans#36]
Hi Thierry

Creating an h1 in the content creation of a post for instance. Having the title so long that it also goes to the second line makes the second line crash into the first. This is a repeatable error.

![screen shot 2016-05-06 at 12 02 42](https://cloud.githubusercontent.com/assets/5323259/15271156/f6a42638-1a3b-11e6-89d4-e09fdf97d339.png)

Btw I would suggest looking at Twenty Sixteen editor style. It has nice space and in general just looks nice. Here is an example:

![screen shot 2016-05-15 at 01 29 13](https://cloud.githubusercontent.com/assets/5323259/15271170/88228668-1a3c-11e6-837e-1b75ec322594.png)

**Comment by ThierryA** [comment]
Thanks for reporting it @paaljoachim. It will definitely be fixed on the next release.

I will update and close this issue as soon as it is fixed ;-)

**Comment by ThierryA** [comment]
Fixed in bd87f413053bb114ed1efc5ccdc503332f592d0e 😄

**Comment by paaljoachim** [comment]
It looks like it is back again.
The following is a new local dev site that uses Beans version 1.4.0 and the default starter child theme version 1.0.0.

Backend:
![screen shot 2017-07-19 at 13 36 58](https://user-images.githubusercontent.com/5323259/28365089-68976b9e-6c87-11e7-8606-c68836bfb5a8.png)

Frontend:
![screen shot 2017-07-19 at 13 37 14](https://user-images.githubusercontent.com/5323259/28365100-729a9da0-6c87-11e7-9bdd-364fdc8180d6.png)

**Comment by ThierryA** [comment]
@paaljoachim I can't seem to reproduce this issue (see [here](https://cloudup.com/cURvbf2xd8I)). Are you still experiencing this issue?

**Comment by paaljoachim** [comment]
I made a new issue. Comparing the default Beans editor stylesheet vs Twenty Sixteen editor stylesheet.
