### ISSUE TITLE
Object of class WP_Error

### ISSUE THREAD

**Issue by alexatbaseagency** [Getbeans/Beans#38]
Hi there,

Latest WP and upon activation of WPML I get the msg:

Notice: Object of class WP_Error could not be converted to int in ~/Projects/wordpress/wp-includes/nav-menu.php on line 366

Deactivating WPML no luck. Changing theme all good.

Any idea?

Thank you
Alex

**Comment by michaelbeers** [comment]
Is this also happening within the original WordPress themes? Because as far i can see its not an issue within Beans but a problem from the WPML plugin

**Comment by alexatbaseagency** [comment]
I was about to post my findings today.

a. Clean installation of WP 4.6 > Beans > WPML > you get the error.
b. Clean installation of WP 4.5.2 > Beans > WPML > no error!!!!
c. Clean installation of WP 4.5.2 > Beans > WPML > upgrade WP 4.6 > no error!!!!

X-Files for ever... ;)

**Comment by ThierryA** [comment]
Hey guys,

WPML does some funny things with the menus to manage multiple languages. I pushed a fix (commit 5c8b8f8cf7086fe08213ccd6a45df4e97002e548) to prevent the PHP warning.

The next beta will be released soon, we are a little bit late on the schedule as my little daughter made it to our world last week :-) You may go ahead a pull from the [development branch](https://github.com/Getbeans/Beans/tree/development) in the mean time.

Happy coding,

**Comment by alexatbaseagency** [comment]
Congratulations mate!!!! Best wishes!!!

**Comment by ThierryA** [comment]
Thanks buddy, much appreciated 😄
