### ISSUE TITLE
Visual hook image?

### ISSUE THREAD

**Issue by paaljoachim** [Getbeans/Beans#4]
Hey

It would be great if you add a visual hook image.

As I am working on adding various widget areas and need to know the name of where I can place each.

Edit. After some digging I found the Structure articles on Hooks.

**Comment by ThierryA** [comment]
Hey there,

The structural hooks are the "bones" hook of the theme. That said, there is a lot more you can do :-)

Basically each markup in Beans has a hook before and after. Once you have enabled the dev mode in WordPress Admin->Settings->Beans, you will find a data-markup-id for each markup when inspecting the page. From there you can suffix it as such:

* **{$markup_id}_before_markup**, fires before the opening markup.
* **{$markup_id}_before_markup**{$markup_id}_prepend_markup</strong>, fires after the opening markup (not available for selfclosed markup).
* **{$markup_id}_before_markup**{$markup_id}_append_markup</strong>, fires before the closing markup (not available for selfclosed markup).
* **{$markup_id}_before_markup**{$markup_id}_afer_markup</strong>, fires after the closing markup.

You can then hook any callback functions to it, for instance outputting the hero widget area anywhere you would like to. Yep, it is real :-)

Hope that helps,
