### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by buddilla** [Getbeans/Beans#40]
There is no license such as GNU GENERAL PUBLIC LICENSE

Please add one

**Comment by ThierryA** [comment]
Hi @buddilla,

Beans is under GPL license. Even thought the license was already declared on [this line](https://github.com/Getbeans/Beans/blob/development/style.css#L11), we just added the [license file here](https://github.com/Getbeans/Beans/blob/development/license.txt) to make it clearer and more official.

Have fun with Beans,
