### ISSUE TITLE
Inactive widgets area Inactive sidebar (Not used) repeated multiple times

### ISSUE THREAD

**Issue by paaljoachim** [Getbeans/Beans#41]
Hey Thierry

I am noticing that the Inactive sidebar (Not used) is repeated multiple times.

![screen shot 2017-07-17 at 11 08 33](https://user-images.githubusercontent.com/5323259/28262520-89c45c1e-6ae3-11e7-88bc-99e0b3a3ab96.png)

I have tested 2 local sites and an online site and they all have the same issue.

I switched to Twenty Sixteen and the error went away.

I believe the cause of the errors is testing out creating widget sections and then jumping between various Beans child themes. It seems to mess up things. 

In a site that had the errors. I removed the Not used widget sections. Logged out and then back in again. The not used sections went away. So my conclusion is then removing the various widget sections inside the not used sections then logging out and then back in again. (Actually I could just refresh the page after having deleted the widget sections and see the Not used sections go away.)

**Comment by itsdanreed** [comment]
This simply means that you had used widget areas from another theme and the inactive sidebars were retained so you could potentially move the widgets to whatever applicable sidebar areas. It's not related to Beans itself.

**Comment by paaljoachim** [comment]
I noticed that refreshing also removed them, so I am closing this issue.
