### ISSUE TITLE
Theme check

### ISSUE THREAD

**Issue by paaljoachim** [Getbeans/Beans#42]
Hey Thierry

I happen to come across this site and checked Beans:
http://themecheck.org/score/wordpress-theme-beans(1).html

**Comment by itsdanreed** [comment]
It looks mostly inaccurate to me.

**Comment by ThierryA** [comment]
@paaljoachim the warnings seems to be trigger by their I18N implementation sniffer which is actually not accurate. The sniffer is picking up Beans functions ending with `_e(` and treat them like if they were the core `_e()` translation function which is actually not the case. Nothing to worry about!
