### ISSUE TITLE
Consider Gulp WP Toolkit

### ISSUE THREAD

**Issue by GaryJones** [Getbeans/Beans#53]
[Gulp WP Toolkit](https://github.com/craigsimps/gulp-wp-toolkit) is something that @craigsimps and myself have been working on, as a way to have the logic for typical theme build processes in an external dependency.

Existing tasks can be adapted via config values, including adapting for a potentially different structure in the theme, and new tasks can be added locally to the theme.

One of the open tickets is to add in a [Sass Compiler](https://github.com/Getbeans/Beans/issues/50) - adding Sass support is something Gulp WP Toolkit can already do - so pull in Gulp WP Toolkit, set the paths, and then run `gulp build:css` to compile the Sass, move it to the right place, handle sourcemaps, potentially RTL style sheets etc.

**Comment by hellofromtonya** [comment]
@GaryJones I've added this to the v2 planning phase.  Right now, Beans uses a LESS PHP compiler.  We need to sit down and work through the best path forward for handling asset compilation.

**Comment by alexadark** [comment]
That's a very good idea, the compiler is ok for small websites, but i was missing sourcemaps, livereloads (for this 2 ones I add a solution on my personal child theme) and autoprefixer.
we need a gulp workflow that bring the same optimizations as with the compiler for people who need it
