### ISSUE TITLE
Consider Theme Toolkit

### ISSUE THREAD

**Issue by GaryJones** [Getbeans/Beans#54]
I've been working on [Theme Toolkit](https://github.com/gamajo/theme-toolkit), which is an external dependency which handles the logic (provides building blocks) for customising config-based themes.

It's relatively new but has been working well for a couple of themes. The _bricks_ here should be applicable to all themes.

There is also a [Genesis Theme Toolkit](https://github.com/gamajo/genesis-theme-toolkit) which extends or adds _bricks_ specific to the Genesis Framework. Whilst that isn't going to be directly useful for Beans, it does show how it can be used to add Beans-specific adaptations that make using the Theme Toolkit easier.

The [Generico](https://github.com/craigsimps/generico) theme by @CraigSimps, as well as my own (non-public) starter theme use it.

The advantage of having a config-based theme, is simply to separate out data, from the logic that consumes that data, making edits easier for non-developers.

**Comment by hellofromtonya** [comment]
Well you know how much I like configuration-based architectures.  Why? It separates implementation from business logic, reduces redundancies, and provides one spot to _configure_ the specifics for the product or app.

I'm adding this request to the v2 project.  Once we start working on that project, we'll look at it and consider how it fits into the overall architecture and objectives.

**Comment by hellofromtonya** [comment]
@GaryJones For v2, the plan is to leap Beans forward to PHP 5.6 as it's minimum base.  [Genesis Theme Toolkit](https://github.com/gamajo/theme-toolkit) has a PHP 7.1 requirement, which will make it incompatible.

I'm going to close this request, but bookmark it for future consideration when we leap forward to PHP 7+.

**Comment by GaryJones** [comment]
> For v2, the plan is to leap Beans forward to PHP 5.6 as it's minimum base.

As I'm sure you're fully aware, the ongoing support for PHP 5.6 ends in less than a month, reducing down to critical security fixes only. There are pros and cons of course, but you'd be targeting a special group of developers (those who care about such things) by targeting at least PHP 7.0 and above, and that can be seen as a definite positive.

Theme Toolkit only requires 7.1 because of the ObjectCalisthenics (see https://github.com/gamajo/theme-toolkit/commit/e88f49d3f55537d0169b2f8b3c062ef8bca195a1), but I'm happy to fix that up if there was serious interest in adopting it for Beans v2.
