### ISSUE TITLE
Code snippets for...

### ISSUE THREAD

**Issue by paaljoachim** [Getbeans/Beans#6]
* Post articles
* Change the post meta information phrases (similar to Genesis). I notice the remove post meta is there.
* Menu. Conditional menu.
* Comments: Change phrases of commenting.
* Change copyright info on the bottom

**Comment by ThierryA** [comment]
Thanks for your feedback, will definitely add it to the list.

Could you give me more details about the following:

* Post articles
* Menu. Conditional menu.

**Comment by paaljoachim** [comment]
What I meant with Post articles has disappeared for me.

For the menu I am thinking something similar to this:
´function gd_nav_menu_args( $args ){
	if( ( 'primary' == $args['theme_location'] ) && is_page( '276' ) ) 	{
		$args['menu'] = 'Sub section menu'; // Add your menu name here. My case it is "Menu for Page"
	}
	return $args;
}

add_filter( 'wp_nav_menu_args', 'gd_nav_menu_args' );

Options
&& is_page(); 
&& is_page (‘id of page’)
&& is_page ('about-me')
&& ( is_archive() || is_singular('page') ) ) —> II brings two options together.
&& is_page_template( ‘name of page template’ ) ´

- Another would be code snippet for search. Change search phrase etc.
- Remove site description.

That's it for now...

**Comment by ThierryA** [comment]
Cool, I have made a note of the other one you added.

Regarding your menu, the 'wp_nav_menu_args' should work just fine.
To remove the site description, just add the line below to your functions.php
```
beans_remove_action( 'beans_site_title_tag' );
```
Thanks,
