### ISSUE TITLE
Inaccurate Count for `beans_count_recursive` with `$count_parent` set to `true`

### ISSUE THREAD

**Issue by hellofromtonya** [Getbeans/Beans#68]
With the `$count_parent` set to `true`, the count is too high and doesn't correlate to the number of elements within the array.

For example, this array has 9 elements in it:

```
array( 1, 2, 3, 4, 5, array( 6, 7, 8, 9 ) )
```

When passing this array into `beans_count_recursive`, it returns a value of 15 elements.

Here is the test for it:

```
// The expect is 9. But the actual is 15.
$this->assertEquals( 9, beans_count_recursive( array( 1, 2, 3, 4, 5, array( 6, 7, 8, 9 ) ), 2 ) );
```

## Why? What is happening?

This line of code counts all of the elements in the array as the starting count:

```
	$count = $count_parent ? count( $array ) : 0;
```

Let's walk the counter:

1. On first pass, the `$count = 6`, as the base array has 6 elements in it.
2. Then we do the `foreach`.  For values `1-5`, the count increments.
3. When it gets to the 5th element, which is an array, the count value is now `$count = 11`.
4. The function is called again (recursive).
5. As the `$depth = 1` now, it counts the number of elements and returns `4`.
6. The `4` is added to the `11`.
7. When it's done, it gives us `15` elements.

## Works with `$parent_count` set to `false`

It works with the `$parent_count` set to `false`.  Why? The initial `$count` is initialized to a value of `0`.

```
// The expect is 9. The actual is 9.
$this->assertEquals( 9, beans_count_recursive( array( 1, 2, 3, 4, 5, array( 6, 7, 8, 9 ) ), 2, false ) );
```

**Comment by hellofromtonya** [comment]
@ThierryA What was the original intent of the variable `$parent_count`?

If I read this correctly, the intent of this function is to allow you granular control of what you want to count, i.e. you can pick a depth to count.  Right?

Okay, so then did you mean for `$count_parent` to **skip over the parent element** when set to `false`, thereby allowing you to count say at depth 2 without the first depth?

**Comment by ThierryA** [comment]
@hellofromtonya I can't recall a specific usage/need for it, in fact this utility function isn't used anywhere on the framework so it may be depreciated, moved to [this file](https://github.com/Getbeans/Beans/blob/development/lib/api/utilities/deprecated.php) and the `$count_parent` argument may be removed.
