### ISSUE TITLE
is this a starter theme, with no styles?

### ISSUE THREAD

**Issue by pknadella** [Getbeans/Beans#7]
is this a starter theme like _s, wth no styles included? I installed it but no styles are applied.....but on the official site it is mentioned that UI kit is included.....

**Comment by ThierryA** [comment]
Hi there,

Style should be applied by default so it seems like there is an issue with your specific install. Could you attached a screenshot?

Do you perhaps have your WordPress install set as such https://davidwinter.me/install-and-manage-wordpress-with-git/?

Thanks,

**Comment by pknadella** [comment]
oh that was quick, :) thanks for a quick reply
I am working on localhost
![firefox_screenshot_2015-09-23t13-36-42 257z](https://cloud.githubusercontent.com/assets/5235237/10046450/6916adfe-6226-11e5-9a21-49931d3696ca.png)
![firefox_screenshot_2015-09-23t13-36-14 722z](https://cloud.githubusercontent.com/assets/5235237/10046452/6cd61ea2-6226-11e5-9d5f-9908c4149df6.png)

**Comment by ThierryA** [comment]
Ok this definitely looks like a path issue with the assets.

Could you tell me a bit more about your local install?
Are you using Mamp, Wamp, VVV or anything else?
Could you also inspect the page, look for the **uikit-css** path path and send it over which will help identifying the issue.

Thanks,

**Comment by pknadella** [comment]
1. using xampp on win10
2. ![fbug](https://cloud.githubusercontent.com/assets/5235237/10046821/a47f99bc-6228-11e5-8bb0-bf3562542390.png)

**Comment by ThierryA** [comment]
Great, thank you for reporting the issue. We are going to start working on that straight away and will report back as soon as it is sorted.

Thanks,

**Comment by ThierryA** [comment]
@pknadella could you kindly send me your email address to thierry[at]getbeans.io so that I can send you the patch for you to test before we push the fix.

Thanks,

**Comment by antonellaP** [comment]
Hi Thierry,
Has this issue been resolved? I tried Beans a couple of days ago and the theme displays unstyled. style.css is empty (except for the comment for WP).   I'm on localhost using Wamp on Windows 8.1.

Thank you

**Comment by ThierryA** [comment]
Hi Antonella,

Have you tried with the latest beta version. [Download the beta version](http://getbeans.io/download-beans-pre-release/?no_cache=1) and give it a try.

Please kindly report if you still get the issue after updating.

Thanks,

**Comment by antonellaP** [comment]
The page is still unstyled.  Here's a screenshot.

Thank you!
![beans-demo](https://cloud.githubusercontent.com/assets/11929250/10163362/b7c8b808-66b2-11e5-9144-25a39171c31f.jpg)

**Comment by ThierryA** [comment]
Thanks, did you make sure to clear the cache in Appearance->Settings?

**Comment by antonellaP** [comment]
Yes, that's been done.

**Comment by ThierryA** [comment]
Could you inspect your page and send a screenshot of the assets path (like pknadella did above)?

**Comment by antonellaP** [comment]
Sure, here it is.
![beans-demo-source](https://cloud.githubusercontent.com/assets/11929250/10164033/3da86a0a-66b7-11e5-954c-e2291e9ffd70.jpg)

**Comment by ThierryA** [comment]
Thanks Antonella, the paths looks correct now. Could you manually remove the **compiler** folder in themesdev/wp-content/uploads/beans/. Then reload the page, do a hard refresh (delete browser cache and stuff).

Thanks again for your testing contribution.

**Comment by antonellaP** [comment]
I removed the folder, flushed the assets cache in the Admin panel, and did a hard refresh, but still no styles.  Thank you for your help.

**Comment by ThierryA** [comment]
Ok, I am going to setup a similar install and will try to reproduce the issue. You haven't tried to move the site onto a server yet right?

**Comment by antonellaP** [comment]
No, it's a demo site for an article I'm writing on Beans, it's only going to be hosted locally.

**Comment by ThierryA** [comment]
Ok cool thanks, will report back as soon as possible:-)

**Comment by antonellaP** [comment]
Fantastic, thank you!

**Comment by ThierryA** [comment]
I have tried to reproduce exactly the same install on Mamp (we work on mac) and I cannot reproduce the error (the joy of local installs). Here is a few more things to try reproducing the error.

* Could you open the link to the UIkit css and printscreen the content?
* Could you take a backup of your site and send it to thierry[at]getbeans.io

Thanks,

**Comment by antonellaP** [comment]
I'll be sending you a backup of the site (it's a demo site that I use to try stuff out).
Here's a screenshot of the UIkit css document.  
![uikit-css](https://cloud.githubusercontent.com/assets/11929250/10166859/4b736c5c-66c6-11e5-99e8-1c2a358c9de4.jpg)

Cheers!

**Comment by ThierryA** [comment]
Great thanks,

**Comment by ThierryA** [comment]
Hi @antonellaP and @pknadella,

First of all, thanks for reporting this issue and contributing to Beans:-) We have setup many Windows installs this morning and did some more testing. We were able to reproduce the issue you faced and fixed it accordingly. Beans 1.2-rc1 is out so you can go ahead and test it. Make sure to clear the cache in Appearance->Settings and do a hard browser refresh.

Please report if you are still experiencing issues.

**Comment by antonellaP** [comment]
I can confirm that the issue is resolved, thank you so much for your amazing support!

**Comment by ThierryA** [comment]
Great Antonella, thanks for your confirmation and kind words :-)

Keep well,
