### ISSUE TITLE
composer.json scripts paths for phpcs and phpunit don't work on Windows.

### ISSUE THREAD

**Issue by christophherr** [Getbeans/Beans#71]
The paths would need backslashes (like the "install-codestandards" path) to work on Windows.

```
   "phpcs-src": "vendor\\bin\\phpcs",
    "phpcs-tests": "vendor\\bin\\phpcs --runtime-set testVersion 5.6 tests\\phpunit\\",
    "phpcs": [
      "@phpcs-src",
      "@phpcs-tests"
    ],
    "test-unit": "vendor\\bin\\phpunit --testsuite unit",
    "test-integration": "vendor\\bin\\phpunit --testsuite integration"
```
I can submit a PR if appropriate.

**Comment by hellofromtonya** [comment]
@christophherr Thanks for catching this problem.  Changing the above to backslashes then makes it not work on Mac or TravisCI. That means we need to think about how to make it Windows developer friendly too.

But before we do that, we need to see how far the problem goes, as the forward slash directory pattern is found in the XML files too for both `phpunit.xml.dist` and `phpcs.xml.dist`.

Do me a favor, in your command line app, type:

```
vendor\bin\phpunit --testsuite unit
```

Does it run?

Then try:

```
vendor\bin\phpcs --runtime-set testVersion 5.6 tests\phpunit\
```

Does that run for you?

**Comment by christophherr** [comment]
@hellofromtonya
Thought that might be a problem ;)
phpcs runs without problem (I'm getting the usual end of line character is invalid - \r\n instead of \n)
phpunit starts to run but throws a fatal error:
```
Fatal error: Uncaught Error: Call to undefined function beans_load_document() in C:\laragon\www\beans\wp-content\themes\Beans\404.php on line 12

Error: Call to undefined function beans_load_document() in C:\laragon\www\beans\wp-content\themes\Beans\404.php on line 12

Call Stack:
    0.0003     367824   1. {main}() C:\laragon\www\beans\wp-content\themes\Beans\vendor\phpunit\phpunit\phpunit:0
    0.0141     889448   2. PHPUnit_TextUI_Command::main() C:\laragon\www\beans\wp-content\themes\Beans\vendor\phpunit\phpunit\phpunit:52
    0.0142     892608   3. PHPUnit_TextUI_Command->run() C:\laragon\www\beans\wp-content\themes\Beans\vendor\phpunit\phpunit\src\TextUI\Command.php:116
    0.1106    3432264   4. PHPUnit_TextUI_TestRunner->doRun() C:\laragon\www\beans\wp-content\themes\Beans\vendor\phpunit\phpunit\src\TextUI\Command.php:186
    1.8299    4271832   5. PHPUnit_Framework_TestSuite->run() C:\laragon\www\beans\wp-content\themes\Beans\vendor\phpunit\phpunit\src\TextUI\TestRunner.php:517
    1.8321    4278880   6. PHPUnit_Framework_TestSuite->run() C:\laragon\www\beans\wp-content\themes\Beans\vendor\phpunit\phpunit\src\Framework\TestSuite.php:722
    1.8332    4279072   7. PHPUnit_Framework_TestSuite->run() C:\laragon\www\beans\wp-content\themes\Beans\vendor\phpunit\phpunit\src\Framework\TestSuite.php:722
    1.8367    4279584   8. Beans\Framework\Tests\UnitTests\API\Utilities\Tests_BeansGet->run() C:\laragon\www\beans\wp-content\themes\Beans\vendor\phpunit\phpunit\src\Framework\TestSuite.php:722
    1.8367    4279584   9. PHPUnit_Framework_TestResult->run() C:\laragon\www\beans\wp-content\themes\Beans\vendor\phpunit\phpunit\src\Framework\TestCase.php:868
    1.8381    4374080  10. SebastianBergmann\CodeCoverage\CodeCoverage->start() C:\laragon\www\beans\wp-content\themes\Beans\vendor\phpunit\phpunit\src\Framework\TestResult.php:650
    1.8381    4374080  11. SebastianBergmann\CodeCoverage\CodeCoverage->initializeData() C:\laragon\www\beans\wp-content\themes\Beans\vendor\phpunit\php-code-coverage\src\CodeCoverage.php:256
    1.8456    4509912  12. include_once('C:\laragon\www\beans\wp-content\themes\Beans\404.php') C:\laragon\www\beans\wp-content\themes\Beans\vendor\phpunit\php-code-coverage\src\CodeCoverage.php:1083```

**Comment by hellofromtonya** [comment]
Okay, good on phpcs.

Now for PHPUnit, make sure you are running the `unit testsuite` only.  From the Beans theme root, did you type:

```
vendor\bin\phpunit --testsuite unit
```

I ask because it's throwing an error on the `404.php` file, which is not in the unit testsuite.

**Comment by christophherr** [comment]
The error is coming from XDebug of all places 
I deactivated the extension and now I'm getting 15 failures
```
C:\laragon\www\beans\wp-content\themes\Beans (development -> origin)
λ vendor\bin\phpunit --testsuite unit
PHPUnit 5.7.25 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.11
Configuration: C:\laragon\www\beans\wp-content\themes\Beans\phpunit.xml.dist
Error:         No code coverage driver is available

Rstring(77) "C:\laragon\www\beans\wp-content\themes\Beans/lib//api/utilities/functions.php"
Rstring(77) "C:\laragon\www\beans\wp-content\themes\Beans/lib//api/utilities/functions.php"
...................................F...FFFFFFFFFFFFFF           55 / 55 (100%)

FAILURES!
Tests: 55, Assertions: 145, Failures: 15, Risky: 2.
```
All Failed asserting that two strings are identical. 
e.g. 
```
-C:\laragon\www\beans\wp-content\themes\Beans\tests\phpunit
+/laragon/www/beans/wp-content/themes/Beans/tests/phpunit
```
(I'm usually getting those with the WP core test suite as well)

**Comment by hellofromtonya** [comment]
It's here:

```
"C:\laragon\www\beans\wp-content\themes\Beans/lib//api/utilities/functions.php"
```

Notice the pathing.  That's why I had you run the tests as I needed to see how deep the Windows filesystem's directory separator went.

Thanks.

**Comment by christophherr** [comment]
The failing unit tests are caused by the Beans functions running through wp_normalize_path which is replacing the backslashes with forward slashes.
Could the 'expected' results be run through wp_normalize_path or a similar replace function and include stripping the Windows drive letter or would this be too close to Circular Reasoning?  
Not sure if this should be discussed in a separate issue.

**Comment by christophherr** [comment]
What would be the downside of removing the vendor/bin path from the scripts?
It works without it for me.

> Note: Before executing scripts, Composer's bin-dir is temporarily pushed on top of the PATH environment variable so that binaries of dependencies are easily accessible. In this example no matter if the phpunit binary is actually in vendor/bin/phpunit or bin/phpunit it will be found and executed.
https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands

**Comment by hellofromtonya** [comment]
@christophherr We use the local version of the dependencies which are available in `vendor/bin`.  Why?  Two reasons:

1. To ensure the right version is used.
2. More importantly, not everyone has `phpcs` and `phpunit` globally on their machine.

Running `phpunit` works for you as I suspect you have a global version installed on your machine or within the localhost container. Right?

## Windows vs. Mac Pathing

Yes, WordPress has a function `wp_normalize_path` that handles the Windows pathing automatically. 

As for the double `lib//api`, that’s an error [found in each of the setups](https://github.com/Getbeans/Beans/blob/development/tests/phpunit/unit-tests/api/utilities/beansGet.php#L29).  Whoopsie.

## Possible Solutions

1.  Add Composer scripts for Windows machines, i.e. possibly with a prefix or suffix of `win`. 
2.  Fix the setup’s opening forward slash bug I noted above.

Give it a try on your machine. See if the above changes work for you.

**Comment by hellofromtonya** [comment]
@christophherr Here's a [proposed fix](https://github.com/hellofromtonya/Beans/tree/windows-fix) for the issues you are having.

Try these on your machine and let me know if they resolve the issue:

- Add "./" before "vendor/bin/" in each of the Composer scripts.  [See it here](https://github.com/hellofromtonya/Beans/blob/windows-fix/composer.json#L44).
- Remove the trailing forward slash from `BEANS_TESTS_LIB_DIR`.  [See it here](https://github.com/hellofromtonya/Beans/blob/windows-fix/tests/phpunit/bootstrap.php#L17)

Thank you for helping test this problem!

**Comment by christophherr** [comment]
Adding `./` results in 
```
 composer test-unit
> ./vendor/bin/phpunit --testsuite unit
'.' is not recognized as an internal or external command,
operable program or batch file.
```
Removing the trailing forwards slash results in 
`Warning: Uncaught file_get_contents(C:\laragon\www\beans\wp-content\themes\Beans/libapi/utilities/functions.php): failed to open stream: No such file or directory`

Not sure if this is a Windows thing but I removed te global installs of phpunit and phpcs and it finds the local version without vendor/bin

**Comment by christophherr** [comment]
> Add Composer scripts for Windows machines, i.e. possibly with a prefix or suffix of win.

I think adding something like `composer test-unit-win` would be easy enough to point out in a readme.

> Fix the setup’s opening forward slash bug I noted above.

Yes, that works 👍  

> Yes, WordPress has a function wp_normalize_path that handles the Windows pathing automatically.

That's why in e.g. https://github.com/Getbeans/Beans/blob/development/tests/phpunit/unit-tests/api/utilities/beansSanitizePath.php#L36-#L37 
`_DIR_` and `BEANS_TESTS_DIR` can never be the same as `beans_sanitize_path( __DIR__ )` and `beans_sanitize_path( BEANS_TESTS_DIR )` 
on a Windows machine

**Comment by hellofromtonya** [comment]
@christophherr I'm thinking that this error:

>Warning: Uncaught file_get_contents(C:\laragon\www\beans\wp-content\themes\Beans/libapi/utilities/functions.php): failed to open stream: No such file or directory

may have been if you corrected the pathing within each test.  The [latest commit I just made](https://github.com/hellofromtonya/Beans/tree/windows-fix) fixes it in the [bootstrap](https://github.com/hellofromtonya/Beans/tree/windows-fix) and each of the tests:

- [Tests_BeansGet](https://github.com/hellofromtonya/Beans/blob/windows-fix/tests/phpunit/unit-tests/api/utilities/beansGet.php#L29)
- [Tests_BeansMultiArrayKeyExists](https://github.com/hellofromtonya/Beans/blob/windows-fix/tests/phpunit/unit-tests/api/utilities/beansMultiArrayKeyExists.php#L29)
- [Tests_BeansPathToUrl](https://github.com/hellofromtonya/Beans/blob/windows-fix/tests/phpunit/unit-tests/api/utilities/beansPathToUrl.php#L30)
- [Tests_BeansRemoveDir](https://github.com/hellofromtonya/Beans/blob/windows-fix/tests/phpunit/unit-tests/api/utilities/beansRemoveDir.php#L30)
- [Tests_BeansRenderFunction](https://github.com/hellofromtonya/Beans/blob/windows-fix/tests/phpunit/unit-tests/api/utilities/beansRenderFunction.php#L30)
- [Tests_BeansRenderFunctionArray](https://github.com/hellofromtonya/Beans/blob/windows-
fix/tests/phpunit/unit-tests/api/utilities/beansRenderFunctionArray.php)
- [Tests_BeansUrlToPath](https://github.com/hellofromtonya/Beans/blob/windows-fix/tests/phpunit/unit-tests/api/utilities/beansUrlToPath.php#L30)

Also, borrowing from WPCS, I've adjusted the [composer scripts](https://github.com/hellofromtonya/Beans/blob/windows-fix/composer.json#L44) to add a leading backslash.  

Give it a try.  This is not a problem we can't overcome, as many open source projects have both Mac and Windows.  Thank you for patience.

**Comment by christophherr** [comment]
I checked out your branch and that seems to do the trick! 🥇 
One thing left:
`c:\laragon\www\beans\wp-content\themes\Beans (windows-fix -> tonya)
λ composer phpcs
> "vendor/bin/phpcs
Script "vendor/bin/phpcs handling the phpcs-src event returned with error code 1`

**Comment by hellofromtonya** [comment]
@christophherr I just pushed a PR #73 that fixes the extra forward slash in the utility unit tests.  We'll create a separate PR to fix running composer scripts on Windows.

**Comment by christophherr** [comment]
Thanks for all your work on this.

**Comment by hellofromtonya** [comment]
@christophherr Now let's focus on the Composer scripts.

What happens when you run:

```
composer test-unit
```

Does it run the unit test suite?

Then check the PHPCS sniffers by running:

```
composer phpcs-tests
```

What happens?  Does it run the PHPCS sniffers on the tests folder?  It should give you something like this:

```
$ composer phpcs-tests
> vendor/bin/phpcs --runtime-set testVersion 5.6 tests/phpunit/
.............. 14 / 14 (100%)

Time: 541ms; Memory: 14Mb
```

**Comment by christophherr** [comment]
Sorry, found one more issue:
`"phpcs-src": "\"vendor/bin/phpcs"`
should be
`"phpcs-src": "\"vendor/bin/phpcs\""`

**Comment by hellofromtonya** [comment]
Hey @christophherr,

Excellent.  Go ahead and adjust the composer scripts using that syntax.  Test that each works on Windows, including the phpunit tests.  Share the code here.  I’ll test it on a Mac.

Once we get it working on both, then you can create a PR for the `composer.json` file changes.  Let’s get you listed as a contributor...WooHoo!

**Comment by christophherr** [comment]
## PHPCS

I'm getting  
` 1 | ERROR | [x] End of line character is invalid; expected "\n" but
   |       |     found "\r\n" (Generic.Files.LineEndings.InvalidEOLChar)`

on every file because I haven't changed my .gitconfic to include
```
[core]
	autocrlf = false
	safecrlf = false
```

**Solution**: Add the above to .gitconfig (and subsequently a note in a readme about it)
**Result**:
```
c:\laragon\www\beans\wp-content\themes\Beans (windows-fix -> tonya)
λ composer phpcs-tests
> "vendor/bin/phpcs" --runtime-set testVersion 5.6 tests/phpunit/
.............. 14 / 14 (100%)
Time: 1.72 secs; Memory: 18Mb
``` 
## phpunit
Will fail 15 tests with the reasons mentioned above.
I added the full output in this gist: https://gist.github.com/christophherr/6702b80af595855958d68b6b2b66d42b

**Comment by christophherr** [comment]
> Excellent. Go ahead and adjust the composer scripts using that syntax. Test that each works on Windows, including the phpunit tests. Share the code here. I’ll test it on a Mac.

Thank you @hellofromtonya.
This works for me on Windows now:
```
  "phpcs-src": "\"vendor/bin/phpcs\"",
    "phpcs-tests": "\"vendor/bin/phpcs\" --runtime-set testVersion 5.6 tests/phpunit/",
    "phpcs": [
      "@phpcs-src",
      "@phpcs-tests"
    ],
    "test-unit": "\"vendor/bin/phpunit\" --testsuite unit",
    "test-integration": "\"vendor/bin/phpunit\" --testsuite integration"
```

I think this is expected but might be worth noting in a readme that 
composer phpcs will run phpcs-src but if there are errors will not run phpcs-tests. 
`Script "vendor/bin/phpcs" handling the phpcs-src event returned with error code 2`

**Comment by hellofromtonya** [comment]
@christophherr and I have both validated that PR #75 resolves the issues that he notes above.  PR #75 is tested on Mac and Windows 10 machines.

Here are the results from @christophherr testing:

```
C:\Code\tm-beans (windows -> origin)
λ composer phpcs-tests
> "vendor/bin/phpcs" --runtime-set testVersion 5.6 tests/phpunit/
.............. 14 / 14 (100%)

Time: 1.75 secs; Memory: 18Mb

C:\Code\tm-beans (windows -> origin)
λ composer test-unit
> "vendor/bin/phpunit" --testsuite unit
PHPUnit 5.7.25 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.11
Configuration: C:\Code\tm-beans\phpunit.xml.dist
Error:         No code coverage driver is available

........................................................          56 / 56 (100%)

Time: 287 ms, Memory: 12.00MB

OK (56 tests, 199 assertions)
```

and results from my iMac:

```
$ composer phpcs-tests
> "vendor/bin/phpcs" --runtime-set testVersion 5.6 tests/phpunit/
.............. 14 / 14 (100%)


Time: 581ms; Memory: 16Mb

hellofromtonya at T-iMac in ~/Sites/beansdev/app/public/wp-content/themes/tm-beans on windows*
$ composer test-unit
> "vendor/bin/phpunit" --testsuite unit
PHPUnit 5.7.25 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.8
Configuration: /Users/hellofromtonya/Sites/beansdev/app/public/wp-content/themes/tm-beans/phpunit.xml.dist
Error:         No code coverage driver is available

........................................................          56 / 56 (100%)

Time: 171 ms, Memory: 10.00MB

OK (56 tests, 199 assertions)
```

**Comment by christophherr** [comment]
Would https://www.appveyor.com/ be an option to run Windows builds in addition to Travis?
