### ISSUE TITLE
How to build theme standalone with child theme.

### ISSUE THREAD

**Issue by minhcanhdn** [Getbeans/Beans#8]
Hi @ThierryA ,

Could you create a guild for how to build standalone with beans. I used Runway frameword, it's has a future to help admin can extract theme standalone from current child theme.

 Thanks so much.

**Comment by ThierryA** [comment]
Hi @minhcanhdn, I am not sure that I understand your question well. What exactly are you trying to achieve?

**Comment by minhcanhdn** [comment]
I mean, May i make standalone themes with beans framework?

**Comment by ThierryA** [comment]
While you can technically take the lib folder and drop it in a standalone theme, Beans is a standalone theme itself and is more meant to be used with child themes.

May I ask what you intend to do which may help me to give you the pros and cons in more details?

**Comment by ThierryA** [comment]
Hi @minhcanhdn, I am going to close this request since we didn't here back from you but feel free to respond anytime and I will gladly re-open it :-)

**Comment by minhcanhdn** [comment]
Thanks @ThierryA I will try it.
