### ISSUE TITLE
"Undefined Index" notice thrown

### ISSUE THREAD

**Issue by n8finch** [Getbeans/Beans#80]
Hey folks! 

If `WP_DEBUG` is set to true, a notice is thrown between the `<main class="tm-main uk-block">...</main>` and `<div class="tm-pre-footer uk-block">...</div>` elements:

`Notice: Undefined index: extension in /srv/www/getbeansio/public_html/wp-content/themes/tm-beans/lib/api/image/class-images.php on line 127`

Looks like this is Beans v 1.4.0 

<img width="988" alt="documentation_ _beans" src="https://user-images.githubusercontent.com/7983116/33446500-d6f9ad2a-d5c5-11e7-8eab-fd27c7bee893.png">

**Comment by ibes** [comment]
the referred file is not existing anymore in the current version of Beans:
https://github.com/Getbeans/Beans/tree/development/lib/api/image

This is the line stated by the error message:
https://github.com/Getbeans/Beans/blob/1.4.0/lib/api/image/class-images.php#L127

Seems like that code ended up here:
https://github.com/Getbeans/Beans/blob/development/lib/api/image/class-beans-image-editor.php#L169

**Comment by hellofromtonya** [comment]
@ibes Would you like to put a check in for this?
