### ISSUE TITLE
Error messages on using a standard Beans child theme.

### ISSUE THREAD

**Issue by paaljoachim** [Getbeans/Beans#82]
Hi

Using Beans and a child theme I am getting these errors:

Warning: Invalid argument supplied for foreach() in /home/easyweb7/public_html/paaljoachimromdahl.com/wp-includes/widgets.php on line 1322

Warning: array_merge(): Argument #3 is not an array in /home/easyweb7/public_html/paaljoachimromdahl.com/wp-includes/widgets.php on line 1159

Warning: array_diff(): Argument #2 is not an array in /home/easyweb7/public_html/paaljoachimromdahl.com/wp-includes/widgets.php on line 1160

Warning: Invalid argument supplied for foreach() in /home/easyweb7/public_html/paaljoachimromdahl.com/wp-includes/widgets.php on line 1162

Warning: array_merge(): Argument #1 is not an array in /home/easyweb7/public_html/paaljoachimromdahl.com/wp-includes/widgets.php on line 1170

Switching over to the default theme of Twenty Seventeen or Twenty Sixteen the error goes away. Switching back again to the Beans child theme the error returns. I switched through the customizer and it was very easy to notice.

It is not fatal so that I can disregard the errors.

**Comment by hellofromtonya** [comment]
Hi Paal,

I'm curious if you get these warnings from your Beans child theme or from the Beans framework?  Do me a favor, please.  Activate the Beans framework (not a child theme) as your theme.  Do you get the warnings?

**Comment by paaljoachim** [comment]
Hey Tonya @hellofromtonya 
I have tested both on a few different sites and the error is not showing up any longer. So I will close this issue.
