### ISSUE TITLE
Post options - Layout

### ISSUE THREAD

**Issue by paaljoachim** [Getbeans/Beans#9]
Hey

In the Layout:
Radio button and the text Use Default. What about turning Use Default into a customizer site layout link? So instead of hesitating how to get to global default there is a direct link to it.

**Comment by ThierryA** [comment]
Hey Paal,

Thanks for the feedback, I have added your suggestion to our new features list :)

**Comment by paaljoachim** [comment]
Great!

**Comment by ThierryA** [comment]
Hey @paaljoachim, just wanted to let you that a "Modify" link has been added as you suggested (see [version 1.2.2](https://github.com/Getbeans/Beans/releases/tag/1.2.2))

Happy coding :)

**Comment by paaljoachim** [comment]
:)
